package pg

import (
	"fmt"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/jackc/pgx/v5"
)

// PlainQuery contains the generated SQL string and a slice of arguments to pass to exec.
type PlainQuery struct {
	SQL  string
	Args []any
}

// BuildUpdate builds an UPDATE query for the given model.
// When fields are given, only these columns are updated. The updated_at column is always set to NOW().
func BuildUpdate[T Model](model T, fields ...string) (*PlainQuery, error) {
	info, v, err := modelFor(model)
	if err != nil {
		return nil, err
	}
	if err := checkUpdate(info, model, fields); err != nil {
		return nil, err
	}

	var sets []string
	var args []any
	for _, field := range info.fields {
		switch {
		case field.name == "id" || field.isCreatedAt:
			// never updated
		case field.isUpdatedAt:
			sets = append(sets, field.quoted+" = NOW()")
		case len(fields) == 0 || slices.Contains(fields, field.name):
			args = append(args, fieldValue(v, field.idx))
			sets = append(sets, field.quoted+" = $"+strconv.Itoa(len(args)))
		}
	}
	args = append(args, model.GetID())

	return &PlainQuery{
		SQL: fmt.Sprintf(
			"UPDATE %s SET %s WHERE %s = $%d RETURNING *",
			info.table(model),
			strings.Join(sets, ", "),
			quotedID,
			len(args),
		),
		Args: args,
	}, nil
}

// BuildInsert builds an INSERT query for the given model.
// When fields are given, only these columns are inserted. The created_at and updated_at columns are always set to NOW().
// The id column is inserted when the model ID is valid, like a UUID set by the application,
// otherwise it is left to the database to generate.
//
// Fields with a zero value, like "", 0, false, a zero time.Time or a nil pointer, slice or map, are not inserted,
// so the database column defaults apply to them, or NULL without a default. This includes the given fields.
// Use a pointer field to insert a zero value, a non-nil pointer to a zero value is inserted.
// When no column is left, the query inserts DEFAULT VALUES.
func BuildInsert[T Model](model T, fields ...string) (*PlainQuery, error) {
	info, v, err := modelFor(model)
	if err != nil {
		return nil, err
	}
	if err := checkFields(info, fields); err != nil {
		return nil, err
	}

	var cols []string
	var values []string
	var args []any
	insertID := model.GetID().Valid()
	for _, field := range info.fields {
		switch {
		case field.name == "id" && !insertID:
			// generated by the database
		case field.name == "id":
			args = append(args, model.GetID())
			cols = append(cols, field.quoted)
			values = append(values, "$"+strconv.Itoa(len(args)))
		case field.isCreatedAt || field.isUpdatedAt:
			cols = append(cols, field.quoted)
			values = append(values, "NOW()")
		case len(fields) == 0 || slices.Contains(fields, field.name):
			value, zero := nonZeroValue(v, field.idx)
			if zero {
				continue // left to the column default
			}
			args = append(args, value)
			cols = append(cols, field.quoted)
			values = append(values, "$"+strconv.Itoa(len(args)))
		}
	}

	if len(cols) == 0 {
		return &PlainQuery{
			SQL: fmt.Sprintf("INSERT INTO %s DEFAULT VALUES RETURNING *", info.table(model)),
		}, nil
	}

	return &PlainQuery{
		SQL: fmt.Sprintf(
			"INSERT INTO %s (%s) VALUES (%s) RETURNING *",
			info.table(model),
			strings.Join(cols, ", "),
			strings.Join(values, ", "),
		),
		Args: args,
	}, nil
}

// BuildDelete builds a DELETE query for the given model by its ID.
func BuildDelete[T Model](model T) (*PlainQuery, error) {
	info, _, err := modelFor(model)
	if err != nil {
		return nil, err
	}
	if err := checkID(info, model); err != nil {
		return nil, err
	}

	return &PlainQuery{
		SQL: fmt.Sprintf(
			"DELETE FROM %s WHERE %s = $1 RETURNING *",
			info.table(model),
			quotedID,
		),
		Args: []any{model.GetID()},
	}, nil
}

// modelFor returns the cached model info and the struct value of the model.
// It returns an error for a nil model, a nil interface or a nil pointer.
func modelFor(model any) (*modelInfo, reflect.Value, error) {
	v := reflect.ValueOf(model)
	if !v.IsValid() {
		return nil, v, Errorf("model is nil")
	}
	if v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return nil, v, Errorf("model %T is nil", model)
		}
		v = v.Elem()
	}
	return globalCache.getModelInfo(v.Type()), v, nil
}

// checkUpdate returns an error when the model cannot be updated with the fields.
func checkUpdate(info *modelInfo, model Model, fields []string) error {
	if info.createOnly {
		return Errorf("model %s is create only", info.name)
	}
	if err := checkID(info, model); err != nil {
		return err
	}
	return checkFields(info, fields)
}

// checkID returns an error when the model ID is not set.
func checkID(info *modelInfo, model Model) error {
	if id := model.GetID(); !id.Valid() {
		return Errorf("model %s has invalid id %q", info.name, id.String())
	}
	return nil
}

// checkFields returns an error when one of the fields is not a writable column of the model.
func checkFields(info *modelInfo, fields []string) error {
	for _, name := range fields {
		f := info.getField(name)
		if f == nil || f.name == "id" || f.isCreatedAt || f.isUpdatedAt {
			return Errorf("model %s has no writable field %q", info.name, name)
		}
	}
	return nil
}

// nonZeroValue returns the field value as a query argument, and whether it is the zero value of the field.
// A field behind a nil embedded struct pointer is zero.
func nonZeroValue(v reflect.Value, idx []int) (any, bool) {
	f, err := v.FieldByIndexErr(idx)
	if err != nil || f.IsZero() {
		return nil, true
	}
	return f.Interface(), false
}

// fieldValue returns the field value as a query argument, or nil when the field is behind a nil embedded struct pointer.
// Values are passed as they are: zero values are written as is, nil pointers, slices and maps are written as NULL.
func fieldValue(v reflect.Value, idx []int) any {
	f, err := v.FieldByIndexErr(idx)
	if err != nil {
		return nil
	}
	return f.Interface()
}

// quotedID is the quoted id column.
var quotedID = QuoteIdent("id")

// QuoteIdent quotes a column name.
func QuoteIdent(name string) string {
	return pgx.Identifier{name}.Sanitize()
}

// QuoteTable quotes a table name. A schema-qualified name like "public.users" is quoted per part.
// A name that already contains double quotes is returned as it is.
func QuoteTable(name string) string {
	if strings.Contains(name, `"`) {
		return name
	}
	return pgx.Identifier(strings.Split(name, ".")).Sanitize()
}
